#include "vst3_instance.h"
#include "memory_stream.h"
#include <cmath>
#include <cstring>
#include <pluginterfaces/base/ipluginbase.h>
#include <pluginterfaces/vst/ivstmessage.h>

extern "C" Steinberg::IPluginFactory* PLUGIN_API GetPluginFactory ();
namespace pvst {
using namespace Steinberg; using namespace Steinberg::Vst;
tresult PLUGIN_API Vst3Instance::HostApplication::queryInterface (const TUID iid, void** out) { if (!out) return kInvalidArgument; *out = nullptr; if (FUnknownPrivate::iidEqual (iid, INLINE_UID_OF(IHostApplication))) { *out = this; addRef (); return kResultOk; } return kNoInterface; }
tresult PLUGIN_API Vst3Instance::HostApplication::getName (String128 name) { constexpr char16_t text[] = u"Prometheos WebVST"; std::memcpy (name, text, sizeof text); return kResultOk; }
tresult PLUGIN_API Vst3Instance::HostApplication::createInstance (TUID, TUID, void** out) { if (out) *out = nullptr; return kNoInterface; }
std::unique_ptr<Vst3Instance> Vst3Instance::create (const TUID class_id, double sample_rate, uint32_t max_frames) { if (!std::isfinite (sample_rate) || sample_rate <= 0 || max_frames == 0 || max_frames > PVST_MAX_PROCESS_FRAMES) return {}; auto instance = std::unique_ptr<Vst3Instance> (new Vst3Instance); instance->max_frames_ = max_frames; return instance->start (class_id, sample_rate) ? std::move (instance) : nullptr; }
bool Vst3Instance::start (const TUID class_id, double sample_rate) {
  auto* factory = GetPluginFactory (); if (!factory || !success (factory->createInstance (class_id, INLINE_UID_OF(IComponent), reinterpret_cast<void**> (&component_))) || !component_ || !success (component_->initialize (&host_))) { release (); return false; }
  if (!success (component_->queryInterface (INLINE_UID_OF(IAudioProcessor), reinterpret_cast<void**> (&processor_))) || !processor_) { release (); return false; }
  TUID controller_id {}; if (success (component_->getControllerClassId (controller_id))) { if (!success (factory->createInstance (controller_id, INLINE_UID_OF(IEditController), reinterpret_cast<void**> (&controller_))) || !controller_ || !success (controller_->initialize (&host_))) { release (); return false; } }
  component_->queryInterface (INLINE_UID_OF(IConnectionPoint), reinterpret_cast<void**> (&component_connection_)); if (controller_) controller_->queryInterface (INLINE_UID_OF(IConnectionPoint), reinterpret_cast<void**> (&controller_connection_)); if (component_connection_ && controller_connection_) { component_connection_->connect (controller_connection_); controller_connection_->connect (component_connection_); }
  has_input_ = component_->getBusCount (kAudio, kInput) > 0; if (component_->getBusCount (kAudio, kOutput) != 1) { release (); return false; } BusInfo output_info {}; if (!success (component_->getBusInfo (kAudio, kOutput, 0, output_info)) || output_info.channelCount != 2 || output_info.busType != kMain) { release (); return false; }
  SpeakerArrangement input = SpeakerArr::kStereo, output = SpeakerArr::kStereo; if (!success (processor_->setBusArrangements (&input, has_input_ ? 1 : 0, &output, 1))) { release (); return false; }
  ProcessSetup setup {}; setup.processMode = kRealtime; setup.symbolicSampleSize = kSample32; setup.maxSamplesPerBlock = PVST_MAX_PROCESS_FRAMES; setup.sampleRate = sample_rate; if (!success (processor_->canProcessSampleSize (kSample32)) || !success (processor_->setupProcessing (setup))) { release (); return false; }
  if (has_input_) component_->activateBus (kAudio, kInput, 0, true); component_->activateBus (kAudio, kOutput, 0, true); if (!success (component_->setActive (true)) || !success (processor_->setProcessing (true))) { release (); return false; }
  input_buses_[0].numChannels = 2; input_buses_[0].channelBuffers32 = input_channels_.data (); output_buses_[0].numChannels = 2; output_buses_[0].channelBuffers32 = output_channels_.data (); return true;
}
Vst3Instance::~Vst3Instance () { release (); }
void Vst3Instance::release () { if (processor_) processor_->setProcessing (false); if (component_) { component_->setActive (false); if (has_input_) component_->activateBus (kAudio, kInput, 0, false); component_->activateBus (kAudio, kOutput, 0, false); } if (component_connection_ && controller_connection_) { component_connection_->disconnect (controller_connection_); controller_connection_->disconnect (component_connection_); } if (controller_) { controller_->terminate (); controller_->release (); controller_ = nullptr; } if (processor_) { processor_->release (); processor_ = nullptr; } if (component_) { component_->terminate (); component_->release (); component_ = nullptr; } if (component_connection_) { component_connection_->release (); component_connection_ = nullptr; } if (controller_connection_) { controller_connection_->release (); controller_connection_ = nullptr; } }
int32_t Vst3Instance::process (const float* input, float* output, uint32_t frames) { if (!output) return PVST_ERROR_ARGUMENT; if (frames > max_frames_ || frames > PVST_MAX_PROCESS_FRAMES) return PVST_ERROR_FRAME_COUNT; input_channels_[0] = const_cast<float*> (input ? input : silence_.data ()); input_channels_[1] = input_channels_[0]; output_channels_[0] = output; output_channels_[1] = output; ProcessData data {}; data.processMode = kRealtime; data.symbolicSampleSize = kSample32; data.numSamples = static_cast<int32> (frames); data.numInputs = has_input_ ? 1 : 0; data.numOutputs = 1; data.inputs = input_buses_.data (); data.outputs = output_buses_.data (); data.inputEvents = &events_; data.inputParameterChanges = &parameters_; const auto result = processor_->process (data); events_.clear (); parameters_.clear (); return success (result) ? PVST_OK : PVST_ERROR_PLUGIN; }
int32_t Vst3Instance::reset () { return processor_->setProcessing (false) == kResultOk && processor_->setProcessing (true) == kResultOk ? PVST_OK : PVST_ERROR_PLUGIN; }
int32_t Vst3Instance::note (bool on, int32_t note, float velocity) { if (note < 0 || note > 127 || !std::isfinite (velocity) || velocity < 0 || velocity > 1) return PVST_ERROR_ARGUMENT; return events_.note (on, note, velocity) ? PVST_OK : PVST_ERROR_QUEUE_FULL; }
int32_t Vst3Instance::set_parameter (uint32_t id, float value) { if (!controller_ || !std::isfinite (value) || value < 0 || value > 1) return PVST_ERROR_ARGUMENT; if (!parameters_.push (id, value)) return PVST_ERROR_QUEUE_FULL; return success (controller_->setParamNormalized (id, value)) ? PVST_OK : PVST_ERROR_ARGUMENT; }
float Vst3Instance::get_parameter (uint32_t id) const { return controller_ ? static_cast<float> (controller_->getParamNormalized (id)) : 0.f; }
bool Vst3Instance::save_state (std::vector<uint8_t>& result) { MemoryStream component, controller; if (!success (component_->getState (&component))) return false; if (controller_ && !success (controller_->getState (&controller))) return false; const auto& a = component.bytes (); const auto& b = controller.bytes (); result.resize (16 + a.size () + b.size ()); const uint32_t header[] {0x54535650u, 1u, static_cast<uint32_t> (a.size ()), static_cast<uint32_t> (b.size ())}; std::memcpy (result.data (), header, sizeof header); std::memcpy (result.data () + 16, a.data (), a.size ()); std::memcpy (result.data () + 16 + a.size (), b.data (), b.size ()); return true; }
bool Vst3Instance::load_state (const uint8_t* data, uint32_t size) { if (!data || size < 16) return false; uint32_t h[4] {}; std::memcpy (h, data, sizeof h); if (h[0] != 0x54535650u || h[1] != 1u || h[2] > size - 16u || h[3] > size - 16u - h[2]) return false; MemoryStream a (data + 16, h[2]), b (data + 16 + h[2], h[3]); if (!success (component_->setState (&a))) return false; a.rewind (); if (controller_ && (!success (controller_->setComponentState (&a)) || !success (controller_->setState (&b)))) return false; return true; }
int32_t Vst3Instance::parameter_count () const { return controller_ ? controller_->getParameterCount () : 0; }
bool Vst3Instance::parameter_info (uint32_t index, ParameterInfo& info) const { return controller_ && success (controller_->getParameterInfo (static_cast<int32> (index), info)); }
bool Vst3Instance::parameter_value_text (uint32_t id, float value, String128 text) const { return controller_ && std::isfinite (value) && success (controller_->getParamStringByValue (id, value, text)); }
} // namespace pvst
